### ISSUE TITLE
Create BBC News Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [Rayman-Sodhi/Clone-IT#200]
### Is your feature request related to a problem? Please describe.

Yes, since this is a website clone

### Describe the solution you'd like.

I will use simple HTML, CSS(Bootstrap Framework) and JS

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76027425/160286479-8e22ff6c-fc6d-405d-a3da-6acf331c9c68.png)

**Comment by gurjeetsinghvirdee** [comment]
Assign to u @Kumar-laxmi

**Comment by gurjeetsinghvirdee** [comment]
Copied content from this repo `https://github.com/robin3317/BBC-News-Website`

I don't think you can make your own clones I have a doubt from the first day how can someone make this much fast,
I check on some sites but it doesn't work due to some js,

@Rayman-Sodhi what to do now 6 PR from this guy all are copied content
