### ISSUE TITLE
Add Facebook and Google Keep Clone to main webste .Link can be found in Readme

### ISSUE THREAD

**Issue by Rayman-Sodhi** [Rayman-Sodhi/Clone-IT#89]
Maintain website by adding new clones once pr's are merged ...

**Comment by gurjeetsinghvirdee** [comment]
Hey, @Rayman-Sodhi Assign me, I will add merged changes into `index` files with the asset so they will preview on the website.

**Comment by Rayman-Sodhi** [comment]
send a ss before pr

**Comment by gurjeetsinghvirdee** [comment]
Sure

**Comment by gurjeetsinghvirdee** [comment]
Hey @Rayman-Sodhi I added these four clones `Google`, `Slack`, `Youtube` & `Facebook`
Google Keep clone was not merged yet because of some conflicts so I didn't add that project to the website & I changed the size of cards `13rem to 15.5rem` because the description was not fit inside in small cards now it's bigger and looks great.

![Screenshot (706)](https://user-images.githubusercontent.com/73753957/156987710-2759ab46-6456-4aaa-a96f-c391ba1863d4.png)
